import type { Opts } from "oazapfts";
import { generateSource } from "oazapfts";
import type { Class, Declarative } from "#/lib/declarative/declarative.ts";
import { getPrototypeValue } from "#/lib/declarative/declarative.ts";
import { createDecoratorFactory } from "#/lib/declarative/decorator.ts";
import type { ValueOpenAPI } from "#/lib/declarative/common/openapi/openapi.ts";

/**
 * generateOazapftsOf returns the source code generated by oazapfts.
 */
export async function generateOazapftsOf<TClass extends Class>(
  target: TClass,
): Promise<string | undefined> {
  return await getPrototypeValue<ValueOazapfts>(target)?.generateOazapfts?.();
}

/**
 * oazapfts is a decorator that generates a TypeScript client for the OpenAPI
 * specification using Oazapfts.
 *
 * @example
 * ```ts
 * @standardCreate()
 * @standardGet()
 * @jsonSchema()
 * class Person {
 *   public constructor(public name: string) {}
 * }
 *
 * @oazapfts({ optimistic: true })
 * @openapi({
 *  specification: {
 *    openapi: "3.0.1",
 *    info: { title: "App", version: "0.0.1" },
 *    components: {},
 *  },
 *  resources: [Person],
 * })
 * class App {}
 *
 * const sourceCode = await generateOazapftsOf(App);
 * await Deno.writeTextFile("client.ts", sourceCode);
 * ```
 */
export const oazapfts: (
  options?: OazapftsOptions | undefined,
) => (target: Class) => Class = oazapftsDecoratorFactory();

/**
 * oazapftsDecoratorFactory is a decorator factory for Oazapfts.
 */
export function oazapftsDecoratorFactory(): (
  options?: OazapftsOptions | undefined,
) => (target: Class) => Class {
  return createDecoratorFactory({
    initialize: (options?: OazapftsOptions) => {
      return [declarativeOazapfts(options)];
    },
  });
}

/**
 * declarativeOazapfts is a declarative for Oazapfts.
 *
 * @see https://github.com/oazapfts/oazapfts
 */
export function declarativeOazapfts<
  TValue extends ValueOazapfts,
>(options?: OazapftsOptions): Declarative<TValue> {
  return (value) => {
    return {
      ...value,
      generateOazapfts: () =>
        generateSource(value?.specification as unknown as string, options),
    } as TValue;
  };
}

/**
 * OazapftsOptions is the options for the Oazapfts decorator.
 */
export type OazapftsOptions = Opts;

/**
 * ValueOazapfts is the value expected by the Oazapfts decorator.
 */
export interface ValueOazapfts extends ValueOpenAPI {
  /**
   * generateOazapfts generates the TypeScript client for the OpenAPI specification
   * via Oazapfts.
   */
  generateOazapfts?: () => Promise<string>;
}
